language: php

sudo: false

matrix:
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer validate

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --configuration=phpunit.xml

notifications:
  email: false
